# Check for setting environment variables for MariaDB containers:
# https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/binary-packages/automated-mariadb-deployment-and-administration/docker-and-mariadb/mariadb-server-docker-official-image-environment-variables
#
# Check for setting up maxscale for MariaDB:
# https://mariadb.com/kb/en/mariadb-maxscale-2402-maxscale-2402-mariadb-maxscale-configuration-guide/ 

services:
  server-1:
    image: mariadb:latest
    container_name: server-1
    command: --server_id=1 --log-bin=binlog 
    environment:
      - MARIADB_DATABASE=inference
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
      - MARIADB_HEALTHCHECK_GRANTS=REPLICA MONITOR

  server-2:
    image: mariadb:latest
    container_name: server-2
    command: --server_id=2 --log-bin=binlog
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_MASTER_HOST=server-1
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
      - MARIADB_HEALTHCHECK_GRANTS=REPLICA MONITOR

  server-3:
    image: mariadb:latest
    container_name: server-3
    command: --server_id=3 --log-bin=binlog 
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MARIADB_MASTER_HOST=server-1
      - MARIADB_REPLICATION_USER=replication_user
      - MARIADB_REPLICATION_PASSWORD=replication_password
      - MARIADB_HEALTHCHECK_GRANTS=REPLICA MONITOR

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    ports:
      - "8989:8989"
      - "3306:4000"
    volumes:
      - ./my-maxscale.cnf:/etc/maxscale.cnf.d/my-maxscale.cnf