FROM eclipse-temurin:21-jre

COPY target/inference-1.0-SNAPSHOT-jar-with-dependencies.jar inference-1.0-SNAPSHOT-jar-with-dependencies.jar

ENTRYPOINT ["java","-jar","/inference-1.0-SNAPSHOT-jar-with-dependencies.jar"]